### ISSUE TITLE
List of filesystems does not get refreshed

### ISSUE THREAD

**Issue by jeanchlopez** [ceph/cephmetrics#130]
Just tested 12.2.1 and was playing with multiple filesystems (CephFS), creating some and deleting some. After I have removed one FS, the list of FS available in the UI isn't updated and if you click on the one that was removed you get to an error page. Not a major issue as by default multiple FS is still disabled by default but just in case.

Restarting the Manager daemon fixes the refresh of the FS list

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib64/ceph/mgr/dashboard/module.py", line 478, in filesystem
    "fs_status": global_instance().fs_status(int(fs_id))
  File "/usr/lib64/ceph/mgr/dashboard/module.py", line 355, in fs_status
    stats = pool_stats[pool_id]
KeyError: 4L

**Comment by zmc** [comment]
@jeanchlopez this traceback is coming from ceph-mgr itself; could you file a bug with Ceph?

**Comment by jeanchlopez** [comment]
Sure
