### ISSUE TITLE
iscsi PR broke collectors

### ISSUE THREAD

**Issue by zmc** [ceph/cephmetrics#94]
```
Aug 08 19:44:54 mira120 collectd[28366]: python plugin: Error importing module "cephmetrics".
Aug 08 19:44:54 mira120 collectd[28366]: Unhandled python exception in importing module: ImportError: No module named rtslib_fb
Aug 08 19:44:54 mira120 collectd[28366]: Traceback (most recent call last):
Aug 08 19:44:54 mira120 collectd[28366]:   File "/usr/lib/collectd/cephmetrics/cephmetrics/__init__.py", line 15, in <module>
Aug 08 19:44:54 mira120 collectd[28366]:     from collectors import (common, iscsi, mon, osd, rgw)
Aug 08 19:44:54 mira120 collectd[28366]:   File "/usr/lib/collectd/cephmetrics/cephmetrics/collectors/iscsi.py", line 8, in <module>
Aug 08 19:44:54 mira120 collectd[28366]:     from rtslib_fb import RTSRoot
Aug 08 19:44:54 mira120 collectd[28366]: ImportError: No module named rtslib_fb
```

**Comment by pcuzner** [comment]
OK - need to conditionally import rtslib...working on this now.

**Comment by pcuzner** [comment]
PR #95 submitted to resolve

**Comment by pcuzner** [comment]
@zmc can you confirm this is now resolved please?

**Comment by zmc** [comment]
It is, thanks!
